### ISSUE TITLE
iOS: mod_page results in "Error downloading module files. Some files might be missing."

### ISSUE THREAD

**Issue by earcanal** [Birkbeck-Computer-Science-Research/moodlemobile2#1]
# Description

![slack_for_ios_upload_480](https://cloud.githubusercontent.com/assets/1086888/13353606/6a77fa36-dc8d-11e5-8764-f8f252106e08.jpg)
# How to reproduce

Select any `page` activity.
# Test results

Tick indicates issue is **present**:
- Birkbeck
  - [x] iOS
  - [ ] Android
- Official Moodle Mobile
  - [ ] iOS
  - [ ] Android
## Results from build 0.0.13

@gkroussos:   [7:08 PM] 
I tested using my phone and it is still the same error. It happens with any page really but I checked it with the assignments page in my module and I also got it with the Human Resource Management module pages. There is nothing in the error log by the way and the actual page seems to be displayed fully and correctly.
/@gkroussos

[This commit](https://github.com/Birkbeck-Computer-Science-Research/moodlemobile2/commit/94cbcd0dc52716f3f9875bb521bb08442eeab9e7), which resolves another issue involved adding in some Cordova modules which I thought were preventing the project from building.  It's possible that their omission was the cause of this issue on iOS.  Note that I needed to run the following as part of this fix 

`ionic plugin add https://github.com/Tunts/WebIntent https://github.com/ti8m/DocumentHandler com.phonegap.plugins.PushPlugin cordova-plugin-customurlscheme --variable URL_SCHEME=moodlemobile`

That changed a few files under `platforms/ios` which you should run your eye over to ensure they don't interfere with the iOS buid.

**Comment by bbkcompsci** [comment]
Following up from the side effects described by Jess, here is another error of access

[Error] XMLHttpRequest cannot load https://moodle.slapp.space/mm.css. Origin http://localhost:8100 is not allowed by Access-Control-Allow-Origin. (x2)

It seems that it cannot pick up mm.css and for this reason cannot format the links properly.

**Comment by earcanal** [comment]
Is that error generated on your phone?  How do you detect it?

The behaviour suggests that the [Content Security Policy](https://github.com/Birkbeck-Computer-Science-Research/moodlemobile2/blob/master/www/index.html) which works on Android, probably `style-src 'self' http://moodle.slapp.space:* 'unsafe-inline'`, is not working on iOS.  I notice that the URL above is `https` whereas the policy allows `http`.  Perhaps iOS is stricter than Android in enforcing the scheme?

Try >= 0.0.14 where I've changed the policy to `style-src 'self' https://moodle.slapp.space:* 'unsafe-inline'`.

**Comment by earcanal** [comment]
Following conversation with @gkroussos, it sounds like there are no Content Security Policy errors when running on an iPhone, so this may not be the source of the issue.

@gkroussos rebuilt using cordova 6.0.0 and ionic 1.7.4 and the bug is still triggered.

Starting point for further debugging is probably [fetchContent() in the mod_page controller](https://github.com/Birkbeck-Computer-Science-Research/moodlemobile2/blob/master/www/addons/mod_page/controllers/index.js#L38)
