### ISSUE TITLE
iOS runtime errors

### ISSUE THREAD

**Issue by bbkcompsci** [Birkbeck-Computer-Science-Research/moodlemobile2#2]
[Error] Refused to load the stylesheet 'https://moodle.slapp.space/fonts/montserrat/stylesheet.css' because it violates the following Content Security Policy directive: "style-src 'self' http://moodle.slapp.space:* 'unsafe-inline'".

[Error] 2/29/2016 10:37:51 AM $mmInitDelegate: Error while calling the init process 'mmEmulator'. TypeError: undefined is not an object (evaluating '$window.webkitStorageInfo.requestQuota')
    (anonymous function)
    enhancedLogFn
    (anonymous function)
    handleCallback
    (anonymous function)
    processQueue
    (anonymous function)
    $eval
    $digest
    $apply
    bootstrapApply
    invoke
    doBootstrap
    bootstrap
    angularInit
    (anonymous function)
    trigger
    eventHandler

[Error] XMLHttpRequest cannot load https://moodle.bbk.ac.uk/local/mobile/check.php. Origin http://localhost:8100 is not allowed by Access-Control-Allow-Origin.

**Comment by earcanal** [comment]
Can you confirm that these errors are observed on your iPhone?

There appear to be multiple issues above:
1. 862d48a146f7a0c66937923db41ee0b79c75f616 should resolve the first error.  As I'm still unfamiliar with iOS builds, I'm assuming that building will make the necessary changes under `platforms/ios/...` and you will push anything that needs to go back in to the repo.
2. I don't understand the second error, but it _may_ (via [emulator.js](https://github.com/Birkbeck-Computer-Science-Research/moodlemobile2/blob/master/www/core/lib/emulator.js) or [init.js](https://github.com/Birkbeck-Computer-Science-Research/moodlemobile2/blob/master/www/core/lib/init.js)) provide a clue to issue #1.  It could also be a red herring!  The fact that issue #1 doesn't arise in the official app tells me it's a config and/or build issue.
3. The third error is another [CORS](http://blog.ionic.io/handling-cors-issues-in-ionic/) issue.  Try a build that includes 12dafa2cbfc4c0efc6fd5ef65270b87e8a140a9c as that may resolve this error _and_ issue #1.  If it doesn't then I would suggest temporarily making the security policy as permissive as possible to see if that resolves these errors.  If it does, then progressively tighten the policy until you're happy with the security side of things and the issue remains resolved.  The canonical docs for resolving content security policies seem to be [cordova-plugin-whitelist](https://github.com/apache/cordova-plugin-whitelist).  The syntax is fiddly so I think it needs a combination of reading the docs, plus trial and error!

**Comment by bbkcompsci** [comment]
The erros also happen on the iphone i.e. I can see the wrong behaviour but they are not logged even when I am connected to xcode under the debugger.

I run the new build and it is still there, so I think we should have a go with the most permissive policy to see if these can be resolved.

You do not push the platforms directory, so I have not pushed it either but the files are generated in the same way as android. You can vnc and have a look if it will help.

George

**Comment by earcanal** [comment]
Summary of conversation with @gkroussos.  These errors are generated under `ionic serve` but _not_ in the xcode debugger when running on an iPhone.  When testing under `ionic serve`, errors 1 and 3 can probably be eliminated using a browser plugin (I use https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en on Chrome).  Error 2 has gone away.
