### ISSUE TITLE
iOS: mod_page links aren't active

### ISSUE THREAD

**Issue by JessicaRimoch** [Birkbeck-Computer-Science-Research/moodlemobile2#3]
When using an iphone to view a page, links (blue, underlined text with href) cannot be clicked on to go to that url. For example, on the 'Human Resource Management MSc: Accepting your offer' module, on the 'Fees and Finance' page, there are various links (which work on android) which all fail on iphone, for example "Find out more about funding and financial support at postgraduate level."

**Comment by bbkcompsci** [comment]
This is the same bug as for issue 1.
